name: Changelog

on:
  workflow_dispatch: # only runs manually

jobs:
  deploy:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3
      - name: âœ¨ Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"
      - name: ğŸšš Restore
        run: dotnet restore "dev/ChangelogPageMaker"
      - name: ğŸ› ï¸ Build
        run: dotnet build "dev/ChangelogPageMaker" --configuration Release --no-restore
      - name: ğŸ§ª Test
        run: dotnet test "dev/ChangelogPageMaker" --no-restore --verbosity minimal
      - name: âœ… Commit Changes
        run: |
          git config --global user.name 'Scott W Harden (via GitHub Actions)'
          git config --global user.email 'swharden@gmail.com'
          git commit -am "Changelog: Automated Update"
          git status
