name: Cookbook

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cook:
    runs-on: windows-latest
    steps:
      # purge cache early so old FTP state json doesn't stick around
      - name: ðŸ§¹ Purge Website Cache
        run: curl --user deploy:${{ secrets.CACHE_PASSWORD }} https://scottplot.net/admin/clear-cache.php

      - name: ðŸ›’ Checkout ScottPlot.NET
        uses: actions/checkout@v2

      - name: ðŸ›’ Checkout ScottPlot Source
        uses: actions/checkout@v2
        with:
          repository: ScottPlot/ScottPlot
          path: ScottPlot

      - name: âœ¨ Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
          include-prerelease: true

      - name: ðŸ› ï¸ Generate Cookbook Images
        working-directory: ./ScottPlot/src/cookbook/ScottPlot.Cookbook
        shell: bash
        run: >
          dotnet run 
            --project "../CookbookGenerator" 
            --cookbookFolder "./" 
            --saveImages "../../../../content/cookbook/4.1/images" 
            --saveSource "../../../../content/cookbook/4.1/source"

      - name: ðŸŒŽ Build Cookbook Pages
        shell: bash
        run: >
          dotnet run 
            --project './dev/SiteBuilder' 
            --content './content' 
            --theme './dev/theme' 
            --cookbook './ScottPlot/src/cookbook/ScottPlot.Cookbook' 
            --urlSource 'https://github.com/ScottPlot/ScottPlot.NET/blob/main/content' 
            --urlSite 'https://scottplot.net'

      - name: ðŸš€ Deploy using FTP
        uses: SamKirkland/FTP-Deploy-Action@65c6a8f943bbf04faf9b59520a103318b418952e # 4.1.0
        with:
          local-dir: ./content/cookbook/4.1/
          server-dir: /scottplot.net/public_html/cookbook/4.1/
          protocol: ftps
          server: scottplot.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          log-level: minimal
          state-name: .ftpStateCookbook1.json
          exclude: "[*.md, *.cs]"

      - name: ðŸ§¹ Purge Website Cache
        run: curl --user deploy:${{ secrets.CACHE_PASSWORD }} https://scottplot.net/admin/clear-cache.php
